apiVersion: v2
name: istiod
description: A Helm chart for install istio on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: istiod
    version: 1.13.0
    repository: https://istio-release.storage.googleapis.com/charts